services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4173:80
    restart: unless-stopped
    networks:
      - codesage

networks:
  codesage:
    driver: bridge
